name: greymuzzle
recipe: drupal9
config:
  webroot: web
  php: '8.1'
  composer_version: '2.3.5'
  database: mysql:5.7
  drush: ^10

excludes:
  - vendor

proxy:
  appserver:
    - greymuzzle.lndo.site
  mailhog:
    - mailhog.lndo.site
  phpmyadmin:
    - phpmyadmin.lndo.site

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  node:
    type: node
    command: npm start
  appserver:
    run:
      - composer install

tooling:
  npm:
    service: node
    cmd: npm install
    description: "Installs all the things"
  "npm:build":
    service: node
    cmd: npm run build
    description: "Builds out CSS from source/css/styles.css to public/css/patterns.css."
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
    description: "Php codesniffer"
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf
    description: "Php code beautifier"
