id: d7_file_entity_source_field_config
label: Media source field instance configuration
migration_tags:
  - Drupal 7
  - Configuration
deriver: Drupal\media_migration\Plugin\migrate\D7FileEntityConfigDeriver
idMap:
  plugin: smart_sql
source:
  plugin: d7_file_entity_source_field_instance
  constants:
    entity_type_id: media
    required: true
process:
  field_name: source_field_name
  entity_type: constants/entity_type_id
  required: 'constants/required'
  bundle: bundle
  label: source_field_label
  settings: settings
destination:
  plugin: entity:field_config
migration_dependencies:
  required:
    - d7_file_entity_source_field
