buttons_size: 16
additional_html: "<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_twitter\"></a>\r\n<a class=\"a2a_button_instagram\" data-a2a-follow=\"greymuzzle\"></a>"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
no_3p: false
entities:
  media: 0
  node: 1
  comment: 1
  block_content: 0
  contact_message: 0
  entity_embed_fake_entity: 0
  file: 0
  menu_link_content: 0
  path_alias: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  paragraph: 0
  paragraphs_library_item: 0
_core:
  default_config_hash: '-oeXHVXl-m1HE6XR_-FXfNgJOgPuHcOCWSkymfOR7Sc'
