features:
  name: 1
  slogan: 1
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo_0.png'
favicon:
  use_default: 1
  path: 'public://favicon_0.ico'
  mimetype: image/vnd.microsoft.icon
mobile_menu_all_widths: 0
site_branding_bg_color: gray
