_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 7e708ff1-2ac9-41ce-921a-46595f5214bf
name: 'The Grey Muzzle Organization'
mail: info@greymuzzle.org
slogan: ''
page:
  403: /node/1710
  404: /node/1710
  front: /node/1710
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
